---
app_path:
debug: true

logger:
  level: debug

server:
  read_timeout: 30
  write_timeout: 30
  shutdown_timeout: 30

listen:
  type: port
  sock_name: app.sock
  bind_ip: 0.0.0.0
  port: 8080

storage:
  type: postgres
  host: 127.0.0.1
  port: 5432
  username: user_pg
  password: 123456
  database: db_pg
  max_pool_size: 2
  timeout: 30

#redis:
#  host: 127.0.0.1
#  port: 6379
#  password: 123456

cors:
  allowed_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed_methods:
    - GET
    - POST
    - PATCH
    - DELETE
  allowed_headers:
    - Content-Type
  # exposed_headers:
  allow_credentials: true

translation:
  dir_path: ./translate
  file_type: yaml
  lang_codes: # the first language is used as fallback
    - en
    - ru