---
privileges:
  - apiAdm

permissions:
  - modCatalogBox
  - modCatalogPaper
  - modCatalogLaminate
  - modControlsElementTemplate
  - modControlsSubmitForm
  - modControlsSubmitFormToPublish
  - modDictionariesLaminateType
  - modDictionariesPaperColor
  - modDictionariesPaperFacture
  - modDictionariesPrintFormat
  - modFileStation
  - modProviderAccounts