---
privileges:
  - apiAdm

permissions:
  - modCatalogBox
  - modCatalogPaper
  - modCatalogLaminate
  - modControlsSubmitForm
  - modControlsFormElement
  - modControlsElementTemplate
  - modDictionariesPaperColor
  - modDictionariesPaperFacture
  - modDictionariesPrintFormat
  - modDictionariesLaminateType
  - modFileStation
  - modProviderAccountsCompanyPage