---
openapi: 3.0.3
info:
  version: 0.1.1
  title: API управления шаблонами полей пользовательских форм
  description: REST API управления шаблонами полей, на основе которых создаются поля используемые в пользовательских формах в формате OpenAPI v3
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Nazarov Andrey
servers:
  - url: http://localhost:8080
    description: Dev Server
tags:
  - name: FormFieldTemplate
    description: Form Field Template

paths:
  /v1/form-field-templates:
    get:
      summary: Метод получения списка шаблонов полей формы
      description: Метод предназначен для получения списка всех шаблонов полей формы, сохраненных в БД
      operationId: getFormFieldTemplates
      tags:
        - FormFieldTemplate

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/App.Request.Header.acceptLanguage"
        - $ref: "#/components/parameters/App.Request.Header.correlationId"
        - $ref: "#/components/parameters/App.Request.Query.ItemStatuses"

      responses:
        "200":
          description: Получен список шаблонов полей формы
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/App.Model.FormFieldTemplate"
        "401":
          $ref: "#/components/responses/App.Response.Error401"
        "403":
          $ref: "#/components/responses/App.Response.Error403"
        "500":
          $ref: "#/components/responses/App.Response.Error5XX"

    post:
      summary: Метод добавления нового шаблона поля формы
      description: Метод предназначен для создания информации о новом шаблоне поля формы в БД
      operationId: createFormFieldTemplate
      tags:
        - FormFieldTemplate

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/App.Request.Header.acceptLanguage"
        - $ref: "#/components/parameters/App.Request.Header.correlationId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/App.Model.FormFieldTemplate"

      responses:
        "201":
          description: Информация о шаблоне поля формы успешно добавлена
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/App.Response.Model.CreateEntity"
        "400":
          # Название переменной записи не может быть пустым
          # Указанное название записи уже существует
          # Название переменной записи не может быть более 32 символов
          # Название переменной записи должны соответствовать следующему шаблону "[a-zA-Z][a-zA-Z0-9]+"
          # Заголовок записи не может быть пустым
          # Заголовок записи не может быть более 128 символов
          # Тип поля формы содержит недопустимое значение
          # Содержание шаблона поля формы не может быть пустым
          # Содержание шаблона поля формы не может быть более 65536 символов
          # Содержание шаблона поля формы некорректно
          $ref: "#/components/responses/App.Response.Error400"
        "401":
          $ref: "#/components/responses/App.Response.Error401"
        "403":
          $ref: "#/components/responses/App.Response.Error403"
        "500":
          $ref: "#/components/responses/App.Response.Error5XX"

  /v1/form-field-templates/{templateId}:
    get:
      summary: Метод получения шаблона поля формы по его идентификатору
      description: Метод предназначен для получения информации о шаблоне поля формы из БД
      operationId: getFormFieldTemplate
      tags:
        - FormFieldTemplate

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/App.Request.Header.acceptLanguage"
        - $ref: "#/components/parameters/App.Request.Header.correlationId"
        - $ref: "#/components/parameters/App.Request.Path.templateId"

      responses:
        "200":
          description: Получена информация о шаблоне поля формы
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/App.Model.FormFieldTemplate"
        "401":
          $ref: "#/components/responses/App.Response.Error401"
        "403":
          $ref: "#/components/responses/App.Response.Error403"
        "404":
          $ref: "#/components/responses/App.Response.Error404"
        "500":
          $ref: "#/components/responses/App.Response.Error5XX"

    put:
      summary: Метод сохранения шаблона поля формы
      description: Метод предназначен для сохранения информации о шаблоне поля формы в БД
      operationId: storeFormFieldTemplate
      tags:
        - FormFieldTemplate

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/App.Request.Header.acceptLanguage"
        - $ref: "#/components/parameters/App.Request.Header.correlationId"
        - $ref: "#/components/parameters/App.Request.Path.templateId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/App.Model.FormFieldTemplate"

      responses:
        "204":
          description: Информация о шаблоне поля формы успешно сохранена
        "400":
          # Название переменной записи не может быть пустым
          # Указанное название записи уже существует
          # Название переменной записи не может быть более 32 символов
          # Название переменной записи должны соответствовать следующему шаблону "[a-zA-Z][a-zA-Z0-9]+"
          # Заголовок записи не может быть пустым
          # Заголовок записи не может быть более 128 символов
          # Тип поля формы содержит недопустимое значение
          # Содержание шаблона поля формы не может быть пустым
          # Содержание шаблона поля формы не может быть более 65536 символов
          # Содержание шаблона поля формы некорректно
          $ref: "#/components/responses/App.Response.Error400"
        "401":
          $ref: "#/components/responses/App.Response.Error401"
        "403":
          $ref: "#/components/responses/App.Response.Error403"
        "404":
          $ref: "#/components/responses/App.Response.Error404"
        "500":
          $ref: "#/components/responses/App.Response.Error5XX"

    delete:
      summary: Метод удаления шаблона поля формы
      description: Метод предназначен для удаления информации о шаблоне поля формы из БД
      operationId: removeFormFieldTemplate
      tags:
        - FormFieldTemplate

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/App.Request.Header.acceptLanguage"
        - $ref: "#/components/parameters/App.Request.Header.correlationId"
        - $ref: "#/components/parameters/App.Request.Path.templateId"

      responses:
        "204":
          description: Информация о шаблоне поля формы успешно удалена
        "401":
          $ref: "#/components/responses/App.Response.Error401"
        "403":
          $ref: "#/components/responses/App.Response.Error403"
        "404":
          $ref: "#/components/responses/App.Response.Error404"
        "500":
          $ref: "#/components/responses/App.Response.Error5XX"

  /v1/form-field-templates/{templateId}/status:
    put:
      summary: Метод изменения статуса шаблона поля формы
      description: Метод предназначен для изменения статуса шаблона поля формы в БД
      operationId: changeFormFieldTemplateStatus
      tags:
        - FormFieldTemplate

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/App.Request.Header.acceptLanguage"
        - $ref: "#/components/parameters/App.Request.Header.correlationId"
        - $ref: "#/components/parameters/App.Request.Path.templateId"

      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/App.Request.Model.ChangeEntityStatus"

      responses:
        "204":
          description: Статус шаблона поля формы успешно изменён
        "400":
          # Указанный статус содержит недопустимое значение
          # В данный статус переключение невозможно
          $ref: "#/components/responses/App.Response.Error400"
        "401":
          $ref: "#/components/responses/App.Response.Error401"
        "403":
          $ref: "#/components/responses/App.Response.Error403"
        "404":
          $ref: "#/components/responses/App.Response.Error404"
        "500":
          $ref: "#/components/responses/App.Response.Error5XX"

components:

  parameters:
    App.Request.Header.acceptLanguage:
      description: https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Accept-Language
      name: Accept-Language
      in: header
      schema:
        type: string
      example: "ru;q=0.9, fr-CH, fr;q=0.8, en;q=0.7, *;q=0.5"

    App.Request.Header.correlationId:
      name: CorrelationID
      in: header
      schema:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
      example: "f7479171-83d2-4f64-84ac-892f8c0aaf48"

    App.Request.Path.templateId:
      name: templateId
      in: path
      required: true
      description: Идентификатор шаблона поля формы
      schema:
        type: integer
      example: 1000

    App.Request.Query.ItemStatuses:
      name: statuses
      in: query
      required: false
      description: Список статусов через ","
      schema:
        type: string
      example: "DRAFT,ENABLED"

  schemas:
    App.Response.Model.Error: # RFC 7807 (Problem Details for HTTP APIs)
      type: object
      required:
        - title
        - detail
        - request
        - time
      properties:
        title:
          description: Краткое описание проблемы, понятное человеку
          type: string
          example: "Entity not found"
        detail:
          description: Описание конкретно возникшей ошибки, понятное человеку
          type: string
          example: "Entity [User] with id = [123456] not found. You MUST use PUT to add entity instead of GET"
        request:
          description: Метод и URL запроса
          type: string
          example: "PUT /users/123456"
        time:
          description: Время возникновения ошибки с точностью до миллисекунд
          type: string
          format: date-time
          example: "2023-01-01T12:00:00.000+02:00"
        errorTraceId:
          description: Идентификатор конкретного возникновения ошибки
          type: string
          example: "5add1be1-90ab5d42-02fa8b1f-672503f2"

    App.Response.Model.ErrorAttribute:
      type: object
      required:
        - id
        - value
      properties:
        id:
          description: Название атрибута, где произошла ошибка
          type: string
          example: "attributeName"
        value:
          description: Описание ошибки
          type: string
          example: "Атрибут не может быть пустым. Указано недопустимое значение атрибута"

    App.Response.Model.CreateEntity:
      type: object
      required:
        - id
      properties:
        id:
          description: Идентификатор созданного ресурса
          type: integer
          example: 1000
        message:
          type: string
          example: "Ресурс был успешно создан"

    App.Request.Model.ChangeEntityStatus:
      type: object
      properties:
        version:
          description: Текущая версия ресурса
          type: number
          example: 7
        status:
          description: Статус в который переключается ресурс
          type: string
          maxLength: 64
          example: "ENABLED"

    App.Model.FormFieldTemplate:
      type: object
      description: |-
        Шаблон пользовательского компонента \
        Спецификация https://printrobot.atlassian.net/wiki/spaces/prdsh/pages/54919268
      properties:
        id: # templateId, get
          type: integer
          example: 1000
        version: # get, store, changeStatus, remove
          description: Текущая версия записи
          type: number
          example: 7
        createdAt: # get
          description: Дата и время сохранения записи
          type: string
          format: date-time
          example: "2023-01-01T12:00:00.000+02:00"
        paramName: # get, create, store
          description: Уникальное имя, которое задаётся при создании записи
          type: string
          # pattern: [a-zA-Z][a-zA-Z0-9]+
          minLength: 4
          maxLength: 32
          example: "TemplateFieldParam"
        caption: # get, create, store
          description: Название записи
          type: string
          maxLength: 128
          example: "Процесс разработки"
        fieldType: # get, create, store
          description: |-
            Тип шаблона:
            - GROUP - объект поле "группа" (пользовательский компонент);
            - FIELDS - объект список полей;
          type: string
          enum:
            - GROUP
            - FIELDS
          example: "GROUP"
        fieldDetailing: # get, create, store
          description: |-
            Детализация данных, используемая шаблоном:
            - NORMAL - пользовательская;
            - EXTENDED - расширенная (для менеджера);
          type: string
          enum:
            - NORMAL
            - EXTENDED
          example: "NORMAL"
        fieldBody: # get, create, store
          description: Json объект шаблона соответсвущего спецификации
          type: string
          maxLength: 65536 # 64Kb
          example: "{\"json\": \"object\"}"
        status: # get, changeStatus
          description: |-
            Текущий статус записи:
            - DRAFT - черновик;
            - ENABLED - используется;
            - DISABLED - отключён;
          type: string
          enum:
            - DRAFT
            - ENABLED
            - DISABLED
          example: "DRAFT"

  responses:
    App.Response.Error400:
      description: Некорректные входные данные. Возвращается список атрибутов с ошибками
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/App.Response.Model.ErrorAttribute"

    App.Response.Error401:
      description: Пользователь не был аутентифицирован
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/App.Response.Model.Error"

    App.Response.Error403:
      description: Пользователю с текущими правами доступ отклонён
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/App.Response.Model.Error"

    App.Response.Error404:
      description: Запрашиваемый ресурс не был найден
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/App.Response.Model.Error"

    App.Response.Error5XX:
      description: Внутренняя ошибка сервера
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/App.Response.Model.Error"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT